"""M1 gate test: projective refinement with full certificate bundles
(arch doc §19 Milestone 1: duality gap, entropy discrepancy, martingale
residual, and projective Cauchy inequality all pass prescribed tolerances).

DGP 2 of §14.1: a diffusion SSFV posterior generated by a *known* bounded
cylindrical potential at the fine level; both levels are calibrated to its
moments on the same frozen paths (self-consistent targets, so the target
noise floor is the MC scale ~ d/sqrt(n_paths), which sets the residual
tolerance below).

The external-DGP calibration (variance-shifted Heston marginals — §14.1
DGP 3) needs the Sobolev-regularized refinement study and is M2 scope.
"""

import json

import numpy as np
import pytest

pytest.importorskip("numpy")

from otf.ssfv.bsde.picard import PicardHopfColeSolver
from otf.ssfv.constraints.hat_family import LambdaPotential, NestedHatFamily
from otf.ssfv.dual.calibrator import AlternatingDualCalibrator
from otf.ssfv.dual.projective_sequence import ProjectiveSequence
from otf.ssfv.posterior.reweight import ReweightedPosterior
from otf.ssfv.prior.heston import HestonPrior

PRIOR = HestonPrior()
FAMILY = NestedHatFamily(k_min=-0.5, k_max=0.5, base_dim=4)
N_PATHS, N_STEPS, T = 8192, 32, 0.5
MOMENT_TOL = 6e-3  # ~ MC noise floor of the self-consistent targets


@pytest.fixture(scope="module")
def setting():
    paths = PRIOR.simulate(N_PATHS, N_STEPS, T, seed=1729)
    solver = PicardHopfColeSolver().for_prior(PRIOR)
    cal = AlternatingDualCalibrator(FAMILY, solver=solver, max_outer=4,
                                    moment_tolerance=2e-3)

    # DGP 2: known potential at the fine level.
    lvl1 = FAMILY.normalize(FAMILY.level(1), paths.x[:, -1])
    nm = lvl1.normalization
    kept = list(nm.kept_indices)
    colbound = (1.0 + np.abs(nm.means[kept])) / nm.stds[kept]
    rng = np.random.default_rng(7)
    lam_star = rng.normal(0.0, 0.5, lvl1.dim) / colbound
    ctx1 = cal.build_context(lvl1, paths)
    sol_star = solver.solve(paths, LambdaPotential(FAMILY, lvl1, lam_star), ctx1)
    post_star = ReweightedPosterior(paths, sol_star)

    def targets_fn(level):
        psi = FAMILY.evaluate_normalized(level, paths.x[:, -1])
        return post_star.weights() @ psi

    seq = ProjectiveSequence(cal)
    runs = seq.run(paths, [0, 1], targets_fn=targets_fn)
    return paths, post_star, runs


def test_moment_residuals_at_noise_floor(setting):
    _, _, runs = setting
    for r in runs:
        assert r.fit.moment_residual_norm < MOMENT_TOL, r.fit.status


def test_entropy_monotone_and_double_entry(setting):
    _, post_star, runs = setting
    h = [r.bundle.entropy.h_lr for r in runs]
    assert h[1] >= h[0] - 1e-4  # nondecreasing across nested levels
    for r in runs:
        # H_EN carries the field-estimation noise as an upward bias
        # (E[zhat^2] = z^2 + noise); the tolerance is the noise floor at
        # these path counts and tightens along the M2 refinement axes.
        assert r.bundle.entropy.discrepancy < 2e-2  # H_LR vs H_EN
    # The fine level's entropy sits at the DGP's scale.
    assert abs(h[1] - post_star.entropy_lr()) < 5e-3


def test_projective_cauchy_certificate(setting):
    _, _, runs = setting
    b = runs[1].bundle.projective
    assert b.n_prev == 0
    assert b.kl_direct is not None and b.delta_h is not None
    # KL(Q_1 | Q_0) <= H_1 - H_0 up to estimation slack.
    assert b.kl_direct <= b.delta_h + 2e-3


def test_duality_gap_and_martingale(setting):
    _, _, runs = setting
    for r in runs:
        assert r.bundle.duality.gap < 1e-2
        assert r.bundle.martingale.forward_error < 5e-3
        assert r.bundle.diagnostics["ess_fraction"] > 0.9


def test_law_recovery_against_the_dgp(setting):
    paths, post_star, runs = setting
    strikes = np.array([0.9, 1.0, 1.1])
    fine = runs[1].posterior
    np.testing.assert_allclose(
        fine.call_prices(strikes), post_star.call_prices(strikes), atol=1e-3,
    )


def test_certificate_bundle_serializes(setting):
    _, _, runs = setting
    payload = runs[1].bundle.to_json()
    round_trip = json.loads(payload)
    assert round_trip["level"] == 1
    assert "duality" in round_trip and "projective" in round_trip
    assert isinstance(round_trip["diagnostics"]["ess_fraction"], float)
