"""M1 gate test: projective refinement with full certificate bundles
(arch doc §19 Milestone 1: duality gap, entropy discrepancy, martingale
residual, and projective Cauchy inequality all pass prescribed tolerances).

DGP 2 of §14.1: a diffusion SSFV posterior generated by a *known* bounded
cylindrical potential at the fine level; both levels are calibrated to its
moments on the same frozen paths (self-consistent targets, so the target
noise floor is the MC scale ~ d/sqrt(n_paths), which sets the residual
tolerance below).

The external-DGP calibration (variance-shifted Heston marginals — §14.1
DGP 3) needs the Sobolev-regularized refinement study and is M2 scope.
"""

import json
import os

import pytest

np = pytest.importorskip("numpy")

from otf.ssfv.bsde.picard import PicardHopfColeSolver
from otf.ssfv.constraints.hat_family import LambdaPotential, NestedHatFamily
from otf.ssfv.dual.calibrator import ReducedMomentMapCalibrator
from otf.ssfv.dual.projective_sequence import ProjectiveSequence
from otf.ssfv.posterior.reweight import ReweightedPosterior
from otf.ssfv.prior.heston import HestonPrior

PRIOR = HestonPrior()
FAMILY = NestedHatFamily(k_min=-0.5, k_max=0.5, base_dim=4)
N_PATHS, N_STEPS, T = 8192, 32, 0.5
MOMENT_TOL = 6e-3  # ~ MC noise floor of the self-consistent targets


@pytest.fixture(scope="module")
def setting():
    paths = PRIOR.simulate(N_PATHS, N_STEPS, T, seed=1729)
    solver = PicardHopfColeSolver().for_prior(PRIOR)
    cal = ReducedMomentMapCalibrator(FAMILY, solver=solver, max_outer=4,
                                    moment_tolerance=2e-3)

    # DGP 2: known potential at the fine level, sup|Phi*| = 0.4.
    lvl1 = FAMILY.normalize(FAMILY.level(1), paths.x[:, -1])
    rng = np.random.default_rng(7)
    lam_star = rng.normal(0.0, 1.0, lvl1.dim)
    lam_star *= 0.4 / LambdaPotential(FAMILY, lvl1, lam_star).sup_norm_exact()
    ctx1 = cal.build_context(lvl1, paths)
    sol_star = solver.solve(paths, LambdaPotential(FAMILY, lvl1, lam_star), ctx1)
    post_star = ReweightedPosterior(paths, sol_star)

    def targets_fn(level):
        psi = FAMILY.evaluate_normalized(level, paths.x[:, -1])
        return post_star.weights() @ psi

    seq = ProjectiveSequence(cal)
    runs = seq.run(paths, [0, 1], targets_fn=targets_fn)
    return paths, post_star, runs


def test_moment_residuals_at_noise_floor(setting):
    _, _, runs = setting
    for r in runs:
        assert r.fit.moment_residual_norm < MOMENT_TOL, r.fit.status


def test_entropy_monotone_and_double_entry(setting):
    _, post_star, runs = setting
    h = [r.bundle.entropy.h_lr for r in runs]
    assert h[1] >= h[0] - 1e-4  # nondecreasing across nested levels
    for r in runs:
        # H_EN carries the field-estimation noise as an upward bias
        # (E[zhat^2] = z^2 + noise); the tolerance is the noise floor at
        # these path counts and tightens along the M2 refinement axes.
        assert r.bundle.entropy.discrepancy < 2e-2  # H_LR vs H_EN
    # The fine level's entropy sits at the DGP's scale.
    assert abs(h[1] - post_star.entropy_lr()) < 5e-3


def test_projective_cauchy_certificate(setting):
    _, _, runs = setting
    b = runs[1].bundle.projective
    assert b.n_prev == 0
    assert b.kl_direct is not None and b.delta_h is not None
    # Signed Cauchy slack H_1 - H_0 - KL(Q_1 | Q_0) >= 0 up to MC slack:
    # a negative value beyond it is a theorem violation, not a magnitude.
    assert b.cauchy_slack is not None
    assert b.cauchy_slack > -2e-3
    # The slack's exact sample decomposition against the coarse potential:
    # slack = moment term - dynamic term, identically on the sample. The
    # identity residual is pure arithmetic and must sit at fp noise —
    # anything larger is a real inconsistency in the certificate chain.
    assert b.cauchy_identity_residual is not None
    assert abs(b.cauchy_identity_residual) < 1e-10


def test_duality_gap_and_martingale(setting):
    _, _, runs = setting
    for r in runs:
        d = r.bundle.duality
        # Signed gap: weak duality requires H_LR - D_n >= 0 up to MC error
        # for admissible laws; for the approximate fit the gap must be
        # *explained* by its two defects exactly (sample identity).
        assert -2e-3 < d.gap < 1e-2
        assert abs(d.duality_identity_residual) < 1e-10
        assert abs(d.moment_defect) < 1e-3  # calibrated: m ~ a
        assert r.bundle.martingale.forward_error < 5e-3
        # E^{Q_n}[N^S_T] = 0: W^S stays a Q_n-martingale (structural).
        assert abs(d.semistatic_defect) < 2e-2
        assert r.bundle.diagnostics["ess_fraction"] > 0.9


def test_law_recovery_against_the_dgp(setting):
    paths, post_star, runs = setting
    strikes = np.array([0.9, 1.0, 1.1])
    fine = runs[1].posterior
    np.testing.assert_allclose(
        fine.call_prices(strikes), post_star.call_prices(strikes), atol=1e-3,
    )


def test_schur_conditioning_certificate(setting):
    """M2: the bundle carries the true reduced (Schur) spectrum from the
    implicit-differentiation Jacobian — identifiable dimension, singular
    range, and the FOC-residual split on/off the identifiable subspace."""
    _, _, runs = setting
    for r in runs:
        c = r.bundle.conditioning
        assert c.identifiable_dim is not None and c.identifiable_dim >= 1
        assert c.reduced_sv_max is not None and c.reduced_sv_min is not None
        assert c.reduced_sv_max >= c.reduced_sv_min >= 0.0
        # Calibrated self-consistent DGP: the identifiable part of the
        # residual sits at the moment tolerance.
        assert c.identifiable_residual_norm < 6e-3


@pytest.mark.skipif(not os.environ.get("SSFV_SLOW"),
                    reason="4-level refinement study (~5-10 min); set SSFV_SLOW=1")
def test_four_level_refinement_plateau(setting):
    """M2 refinement table: with the DGP potential at level 1, the
    calibrated entropy must *plateau* from level 1 on — levels 2 and 3
    add constraints the DGP posterior already satisfies, so H_n increases
    toward H* and stops there (I-projection monotonicity). Every
    consecutive pair carries its Cauchy certificate with the exact-sample
    decomposition.

    Sobolev regularization is ON: its measured M2 role (D12) is exactly
    here — without it the potential representative loads high-amplitude
    rough columns that are gauge at the coarse resolution but poison the
    finer level's warm start (measured cascade to H ~ 1.9 vs H* ~ 1e-3;
    with sigma^2 = 1e-3 the plateau holds and sup|Phi| stays bounded)."""
    paths, post_star, _ = setting
    solver = PicardHopfColeSolver().for_prior(PRIOR)
    cal = ReducedMomentMapCalibrator(FAMILY, solver=solver, max_outer=4,
                                     moment_tolerance=2e-3,
                                     sobolev_sigma2=1e-3)

    def targets_fn(level):
        psi = FAMILY.evaluate_normalized(level, paths.x[:, -1])
        return post_star.weights() @ psi

    runs = ProjectiveSequence(cal).run(paths, [0, 1, 2, 3], targets_fn=targets_fn)
    h = [r.bundle.entropy.h_lr for r in runs]
    h_star = post_star.entropy_lr()
    # Monotone up to MC noise, bounded by the DGP entropy, plateau after
    # the DGP's own level.
    for a, b in zip(h, h[1:]):
        assert b >= a - 1e-3
    assert h[3] <= h_star + 5e-3
    assert abs(h[3] - h[1]) < 5e-3  # plateau: levels 2,3 add nothing
    for r in runs[1:]:
        b = r.bundle.projective
        assert b.cauchy_slack is not None and b.cauchy_slack > -2e-3
        assert abs(b.cauchy_identity_residual) < 1e-9
        assert r.bundle.diagnostics["ess_fraction"] > 0.5


def test_certificate_bundle_serializes(setting):
    _, _, runs = setting
    payload = runs[1].bundle.to_json()
    round_trip = json.loads(payload)
    assert round_trip["level"] == 1
    assert "duality" in round_trip and "projective" in round_trip
    assert isinstance(round_trip["diagnostics"]["ess_fraction"], float)
